[package]
name = "proyecto_final_ldp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2="0.5.0"
aes-gcm-siv="0.11.1"
rand_chacha="0.3.1"
base64="0.21.2"
